# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/xenolf/lego"
  revision = "fad2257e11ae4ff31ed03739386873aa405dec2d"

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "067529f716f4c3f5e37c8c95ddd59df1007290ae"

[[constraint]]
  name = "github.com/cskr/pubsub"
  version = "1.0.1"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "~1.6.1"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/mholt/caddy"
  branch = "master"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "stash.kopano.io/kc/libkcoidc"
  version = "0.4.3"

[[constraint]]
  name = "stash.kopano.io/kgol/rndm"
  version = "~1.0.0"

[[constraint]]
  name = "stash.kopano.io/kwm/kwmserver"
  version = "0.4.0"
